In [4]:
# Create a personal R library folder
dir.create("~/R/library", recursive = TRUE, showWarnings = FALSE)

#Set .libPaths() for this session
.libPaths("~/R/library")

# Installing packages that are a part of the tidyverse using R code
install.packages ("dplyr", lib="~/R/library")
install.packages ("tidyr", lib="~/R/library")
install.packages ("ggplot2", lib="~/R/library")
install.packages(c("readxl", "readr"), lib="~/R/library")

#load dply, tidyr, ggplot2, and readxl
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)
library(readr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [5]:
# Set the working directory
setwd("/home/user/Capstone/data_center_research")

# Get the working directory
getwd()

[1] "/home/user/Capstone/data_center_research_r"

In [6]:
# List the files in the working directory

list.files(recursive = TRUE)

 [1] "data/analysis/README.txt"
 [2] "data/archive/README.txt"
 [3] "data/metadata/README.txt"
 [4] "data/outputs/README.txt"
 [5] "data/processed/README.txt"
 [6] "data/raw_data/issued_air_permits.csv"
 [7] "data/raw_data/issued_air_permits.xlsx"
 [8] "data/raw_data/README.txt"
 [9] "scripts/air_quality_permits.ipynb"
[10] "scripts/README.md"
[11] "scripts/README.txt"

In [7]:
# List the files that contain the word "issued" to identify path to the issued_air_permits .xlsx dataset

list.files(recursive = TRUE, pattern = "issued", ignore.case = TRUE)

[1] "data/raw_data/issued_air_permits.csv"
[2] "data/raw_data/issued_air_permits.xlsx"

In [8]:
# convert .csv to a dataframe
df <- read.csv("data/raw_data/issued_air_permits.csv", header = FALSE)

# assign correct column names
colnames(df) <- c(
  "air_site_name",
  "registration_no.",
  "permit_issuance_date",
  "program_type",
  "city_or_county",
  "regional_office"
)

In [9]:
# display the dataframe
head(df,10)

   air_site_name                                   registration_no.
1  Northrop Grumman Systems Corporation            11541
2  DP Facilities Inc South LLC                     11790
3  Microsoft Corporation - East Coast Data Center  21527
4  Microsoft Corporation - East Coast Data Center  21527
5  TECfusions Clarksville LLC                      30142
6  Equinix, LLC - CU 1-4                           41064
7  QTS Richmond Data Center                        51232
8  11751 Meadowville Owner LLC c/o GFH Capital Ltd 52173
9  Capital One Services Incorporated               52281
10 Peak 10 Incorporated                            52299
   permit_issuance_date program_type         city_or_county
1  05/16/2008           Article 6 - mNSR     Russell County
2  08/23/2016           Article 6 - mNSR     Wise County
3  04/24/2024           Article 1 - Title V  Mecklenburg County
4  09/19/2023           Article 6 - mNSR     Mecklenburg County
5  02/12/2025           Article 6 - mNSR     Mecklenburg County
6  08/10/2018           Article 6 - mNSR     Culpeper County
7  06/24/2024           Article 6 - mNSR     Henrico County
8  03/23/2007           Article 6 - mNSR     Chesterfield County
9  07/10/2025           Article 6 - mNSR     Henrico County
10 09/12/2013           Article 6 - mNSR     Henrico County
   regional_office
1  Southwest
2  Southwest
3  Piedmont
4  Piedmont
5  Piedmont
6  Northern
7  Piedmont
8  Piedmont
9  Piedmont
10 Piedmont

In [10]:
# checking the column names
names(df)

[1] "air_site_name"        "registration_no."     "permit_issuance_date"
[4] "program_type"         "city_or_county"       "regional_office"

In [11]:
# Check the exact values in city_or_county for extra spaces or different capitalizations
unique(df$city_or_county)

 [1] "Russell County "         "Wise County "
 [3] "Mecklenburg County "     "Mecklenburg County  "
 [5] "Culpeper County "        "Henrico County "
 [7] "Chesterfield County "    "Chesterfield County  "
 [9] "Hanover County "         "Virginia Beach City"
[11] "Accomack County "        "Fairfax County "
[13] "Loudoun County  "        "Prince William County "
[15] "Prince William County  " "Loudoun County "
[17] "Fairfax County  "        "Loudoun County"
[19] "Fairfax County"          "Prince William "
[21] "Manassas City "          "Fauquier County "
[23] "Spotsylvania County "    "Louisa County "
[25] "Stafford County "        "Frederick County "
[27] "Harrisonburg City "

In [12]:
library(stringr)

# trim spaces from city_or_county
df <- df %>%
  mutate(city_or_county = str_trim(city_or_county))  # Trim spaces

# Verify the cleaned column values
unique(df$city_or_county)

 [1] "Russell County"        "Wise County"           "Mecklenburg County"
 [4] "Culpeper County"       "Henrico County"        "Chesterfield County"
 [7] "Hanover County"        "Virginia Beach City"   "Accomack County"
[10] "Fairfax County"        "Loudoun County"        "Prince William County"
[13] "Prince William"        "Manassas City"         "Fauquier County"
[16] "Spotsylvania County"   "Louisa County"         "Stafford County"
[19] "Frederick County"      "Harrisonburg City"

In [13]:
#filter to include only Loudoun County, Prince William County, and Fairfax County; use of the operator %in% to check if elements of one vector are present in another vector. It returns a logical vector (TRUE or FALSE) for each element, and only rows where it’s TRUE are returned.
local_air_permits <- df %>%
  filter(city_or_county %in% c("Loudoun County", "Prince William County", "Fairfax County"))
local_air_permits

    air_site_name
1   Tysons Enterprise West, LLC
2   Tysons Enterprise West, LLC
3   Coresite Real Estate 12100 Sunrise Valley Drive
4   Verizon Business Network Services, Inc.
5   Oath, Inc.
6   Comcast Cablevision of Virginia Incorporated
7   H5 Data Centers (Chantilly)
8   Freddie Mac Corporation
9   22810-22860 International Drive LLC
10  21110 Ridgetop Circle LLC
11  Digital Realty - Lemur Properties, LLC (VA3)
12  RREEF America REIT II Corp. VVV
13  Digital Realty - Porpoise Ventures LLC (VA4)
14  Equinix LLC
15  Equinix, LLC - DC 14
16  Equinix, LLC - DC 14
17  Valo Park
18  Equinix LLC
19  1571 Beaumeade Circle LLC
20  22995 Wilder Court LLC
21  Amazon Data Services, Inc. IAD-1 IAD-9
22  Science Applications International Corp (SAIC)
23  VeriSign Incorporated Broad Run Facility2
24  Amazon Data Services, Inc. IAD-6 IAD-13 IAD-54
25  Inova Health Care Systems - IT Operations
26  New Dominion Technology Park II LLC
27  Digital Realty - Ashburn Campus
28  Digital Realty - Ashburn Campus
29  Digital Realty - Ashburn Campus
30  VPLS
⋮   ⋮
115 ASH2 Lockridge Data Center - QTS Investment Properties Ashburn II LLC
116 Darab Ventures One LLC
117 Cologix ASH1
118 Microsoft - Gainesville Data Center - MNZ03
119 Microsoft - Manassas Data Center - MNZ01
120 Amazon Data Services Inc - IAD-134/135/136
121 Gainesville Crossing Data Campus
122 Vantage Data Centers VA2 LLC
123 Amazon Data Services Inc IAD-169/179
124 Aligned Data Centers IAD03
125 Amazon Data Services Inc IAD-156
126 Amazon Data Services IAD-215
127 NTT Global Data Centers VA10 LLC
128 Digital Realty - Sterling Premiere LLC
129 Yondr Data Center
130 STACK Infrastructure - SI NVA06A LLC
131 Amazon Data Services Inc - DCA-064
132 Amazon Data Services Inc - IAD-165/166/167/168/613
133 Amazon Data Services Inc IAD-124/125/126/127
134 H5 Data Centers - Ashburn
135 Amazon Data Services Inc IAD-195/196/197/198
136 Amazon Data Services Inc IAD-210/211
137 Vantage Data Center VA3 LLC
138 Vantage Data Centers VA16 LLC
139 CyrusOne – NVA14
140 Amazon Data Services Inc - IAD - 500/501
141 Amazon Data Services Inc - IAD-667, IAD-668, IAD-669, IAD-670, and IAD-671
142 MECP1 Ashburn 2, LLC
143 1501 Moran Road Development Owner, LLC
144 Amazon Data Services Inc - IAD-180
    registration_no. permit_issuance_date program_type
1   71804            02/27/2009           Article 5 - SOP
2   71804            11/09/2016           Article 6 - mNSR
3   72296            01/31/2013           Article 6 - mNSR
4   72367            02/26/2020           Article 6 - mNSR
5   72368            08/28/2009           Article 6 - mNSR
6   72374            03/27/2014           Article 6 - mNSR
7   72375            04/04/2014           Article 6 - mNSR
8   73105            07/26/2007           Article 6 - mNSR
9   73158            09/16/2003           Article 6 - mNSR
10  73160            10/30/2019           Article 6 - mNSR
11  73162            03/05/2010           Article 6 - mNSR
12  73170            11/22/2000           Article 6 - mNSR
13  73180            08/07/2008           Article 6 - mNSR
14  73199            04/28/2009           Article 6 - mNSR
15  73200            10/19/2006           Article 6 - mNSR
16  73200            10/18/2007           Article 6 - mNSR
17  73230            01/09/2009           Article 5 - SOP
18  73233            03/19/2024           Article 6 - mNSR
19  73240            09/24/2024           Article 6 - mNSR
20  73293            08/12/2010           Article 6 - mNSR
21  73294            10/11/2024           Article 6 - mNSR
22  73326            07/14/2005           Article 6 - mNSR
23  73341            07/25/2008           Article 6 - mNSR
24  73355            05/19/2025           Article 6 - mNSR
25  73363            07/16/2014           Article 6 - mNSR
26  73369            09/26/2007           Article 6 - mNSR
27  73370            08/27/2013           Article 6 - mNSR
28  73370            12/07/2016           Article 6 - mNSR
29  73370            08/23/2017           Article 6 - mNSR
30  73567            11/07/2007           Article 6 - mNSR
⋮   ⋮                ⋮                    ⋮
115 74232            08/05/2024           Article 6 - mNSR
116 74234            10/31/2025           Article 6 - mNSR
117 74235            07/23/2025           Article 6 - mNSR
118 74236            08/05/2024           Article 6 - mNSR
119 74237            01/17/2024           Article 6 - mNSR
120 74239            09/09/2022           Article 6 - mNSR
121 74241            10/07/2024           Article 6 - mNSR
122 74242            09/15/2023           Article 6 - mNSR
123 74244            45531                Article 6 - mNSR
124 74247            01/06/2023           Article 6 - mNSR
125 74250            06/24/2025           Article 6 - mNSR
126 74252            06/08/2023           Article 6 - mNSR
127 74260            11/03/2023           Article 6 - mNSR
128 74264            09/20/2024           Article 6 - mNSR
129 74265            10/22/2024           Article 6 - mNSR
130 74269            06/18/2024           Article 6 - mNSR
131 74272            10/25/2023           Article 6 - mNSR
132 74273            12/19/2023           Article 6 - mNSR
133 74274            12/27/2023           Article 6 - mNSR
134 74276            11/13/2023           Article 6 - mNSR
135 74277            08/21/2025           Article 6 - mNSR
136 74278            10/31/2023           Article 6 - mNSR
137 74284            03/27/2024           Article 6 - mNSR
138 74287            10/15/2024           Article 6 - mNSR
139 74290            11/01/2024           Article 6 - mNSR
140 74300            03/12/2025           Article 6 - mNSR
141 74301            03/12/2025           Article 6 - mNSR
142 74306            45918                Article 6 - mNSR
143 74315            04/15/2025           Article 6 - mNSR
144 74323            09/10/2025           Article 6 - mNSR
    city_or_county        regional_office
1   Fairfax County        Northern
2   Fairfax County        Northern
3   Fairfax County        Northern
4   Loudoun County        Northern
5   Prince William County Northern
6   Prince William County Northern
7   Fairfax County        Northern
8   Fairfax County        Northern
9   Loudoun County        Northern
10  Loudoun County        Northern
11  Fairfax County        Northern
12  Fairfax County        Northern
13  Prince William County Northern
14  Loudoun County        Northern
15  Prince William County Northern
16  Prince William County Northern
17  Fairfax County        Northern
18  Loudoun County        Northern
19  Loudoun County        Northern
20  Loudoun County        Northern
21  Fairfax County        Northern
22  Fairfax County        Northern
23  Loudoun County        Northern
24  Loudoun County        Northern
25  Loudoun County        Northern
26  Fairfax County        Northern
27  Loudoun County        Northern
28  Loudoun County        Northern
29  Loudoun County        Northern
30  Fairfax County        Northern
⋮   ⋮                     ⋮
115 Loudoun County        Northern
116 Loudoun County        Northern
117 Loudoun County        Northern
118 Prince William County Northern
119 Prince William County Northern
120 Fairfax County        Northern
121 Prince William County Northern
122 Loudoun County        Northern
123 Loudoun County        Northern
124 Loudoun County        Northern
125 Loudoun County        Northern
126 Loudoun County        Northern
127 Prince William County Northern
128 Loudoun County        Northern
129 Loudoun County        Northern
130 Loudoun County        Northern
131 Fairfax County        Northern
132 Fairfax County        Northern
133 Loudoun County        Northern
134 Loudoun County        Northern
135 Prince William County Northern
136 Prince William County Northern
137 Loudoun County        Northern
138 Loudoun County        Northern
139 Loudoun County        Northern
140 Fairfax County        Northern
141 Loudoun County        Northern
142 Loudoun County        Northern
143 Loudoun County        Northern
144 Loudoun County        Northern